/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo.adminInterface;

import deposito.SystemAdministrator;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author tomma
 */
public class ManageSkillDB extends javax.swing.JFrame {

    /**
     * Creates new form ManageSkillDB
     */
    private SystemAdministrator admin;
    public ManageSkillDB() {
        initComponents();
        this.setTitle("Gestione skill Database");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        skillList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    public ManageSkillDB(JFrame parent,SystemAdministrator admin){
        this();
        this.admin=admin;
        refreshCompetenze();
        this.addWindowListener( new WindowListener () {
            @Override
            public void windowOpened(WindowEvent we) {
            }

            @Override
            public void windowClosing(WindowEvent we) {
                parent.setVisible(true);
            }

            @Override
            public void windowClosed(WindowEvent we) {
            }

            @Override
            public void windowIconified(WindowEvent we) {
            }

            @Override
            public void windowDeiconified(WindowEvent we) {
            }

            @Override
            public void windowActivated(WindowEvent we) {
            }

            @Override
            public void windowDeactivated(WindowEvent we) {
            }
        } );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancel = new javax.swing.JButton();
        tfSkill = new javax.swing.JTextField();
        btAddSkill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        skillList = new javax.swing.JList<>();
        btDeleteSkill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCancel.setText("CANCEL");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btAddSkill.setText("AGGIUNGI SKILL");
        btAddSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddSkillActionPerformed(evt);
            }
        });

        skillList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(skillList);

        btDeleteSkill.setText("RIMUOVI SKILL");
        btDeleteSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteSkillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btDeleteSkill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(btAddSkill)
                            .addComponent(tfSkill))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAddSkill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeleteSkill))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void errorMsg(String title,String msg){
        JOptionPane.showMessageDialog(this, msg, title, JOptionPane.ERROR_MESSAGE);
    }
    
    private void btAddSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddSkillActionPerformed
        // TODO add your handling code here:
        String skill=tfSkill.getText();
        String trimmedSkill=skill.trim();
        if(trimmedSkill.equals("")){
            errorMsg("errore","stringa skill vuota");
        }else{
            List<String> skillList=new ArrayList<>();
            skillList.add(trimmedSkill);
            if(admin.createCompetenze(skillList)==null){
                errorMsg("errore","errore aggiunta elementi al db");
            }
            tfSkill.setText("");
        }
        
        refreshCompetenze();
    }//GEN-LAST:event_btAddSkillActionPerformed
    
    private void refreshCompetenze(){
        DefaultListModel lm=new DefaultListModel();
        List<String> skills= admin.viewCompetenze();
        if (skills==null){
            errorMsg("errore", "errore accesso al db");
        }else{
            for(String skill:skills){
                lm.addElement(skill);
            }

            skillList.setModel(lm);
        }
        
    }
    
    private void btDeleteSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteSkillActionPerformed
        // TODO add your handling code here:
        String skill=skillList.getSelectedValue();
        if(skill==null){
            errorMsg("errore", "nessun elemento selezionato");
            return;
        }
        ArrayList<String> competenze=new ArrayList<>();
        competenze.add(skill);
        if(admin.cancellaCompetenze(competenze)==null){
            errorMsg("errore", "errore eliminazione elementi dal db");
        }
        refreshCompetenze();
    }//GEN-LAST:event_btDeleteSkillActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSkillDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSkillDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSkillDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSkillDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSkillDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddSkill;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDeleteSkill;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> skillList;
    private javax.swing.JTextField tfSkill;
    // End of variables declaration//GEN-END:variables
}
